-- Create table for storing comments per wallet address (no RLS policies here)
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  address text not null check (address ~ '^0x[0-9a-fA-F]{40}$'),
  content text not null check (char_length(content) > 0),
  created_at timestamp with time zone not null default now()
);

-- Helpful index for querying by address and time (used by the app)
create index if not exists idx_comments_address_created_at
  on public.comments(address, created_at desc);


